import {
  getAllActiveSessions, getTeachings, getActiveWorktrees, getRecentUsage,
} from "../db.ts";
import type { ActiveProcessMap } from "../types.ts";

export function buildBlocks(text: string, threadKey: string, showStop: boolean): any[] {
  const blocks: any[] = [
    { type: "section", text: { type: "mrkdwn", text: text || " " } },
  ];
  if (showStop) {
    blocks.push({
      type: "actions",
      elements: [
        {
          type: "button",
          text: { type: "plain_text", text: "Stop" },
          style: "danger",
          action_id: "stop_claude",
          value: threadKey,
        },
      ],
    });
  }
  return blocks;
}

export function buildStopOnlyBlocks(threadKey: string): any[] {
  return [{
    type: "actions",
    elements: [{
      type: "button",
      text: { type: "plain_text", text: "Stop" },
      style: "danger",
      action_id: "stop_claude",
      value: threadKey,
    }],
  }];
}

export function buildFeedbackBlock(sessionKey: string): any {
  return {
    type: "context_actions",
    elements: [{
      type: "feedback_buttons",
      action_id: "response_feedback",
      positive_button: {
        text: { type: "plain_text", text: "\ud83d\udc4d" },
        value: `positive:${sessionKey}`,
      },
      negative_button: {
        text: { type: "plain_text", text: "\ud83d\udc4e" },
        value: `negative:${sessionKey}`,
      },
    }],
  };
}

export function buildDisclaimerBlock(): any {
  return {
    type: "context",
    elements: [{
      type: "mrkdwn",
      text: "Generated by Claude. Verify important information.",
    }],
  };
}

export function buildSuggestedPrompts(cwd: string | null): { prompts: any[]; title: string } {
  return {
    prompts: [
      {
        title: "Explain this codebase",
        message: "Give me a high-level overview of this project's architecture, key files, and how the code is organized.",
      },
      {
        title: "Find and fix bugs",
        message: "Look for potential bugs, race conditions, or error-handling issues in the codebase and suggest fixes.",
      },
      {
        title: "Write tests",
        message: "Identify code lacking test coverage and write comprehensive tests for the most critical paths.",
      },
      {
        title: "Refactor code",
        message: "Suggest refactoring opportunities to improve readability, maintainability, and performance.",
      },
    ],
    title: cwd ? `Working in ${cwd}` : "What would you like to do?",
  };
}

export function buildHomeBlocks(activeProcesses: ActiveProcessMap): any[] {
  const sessions = getAllActiveSessions();
  const teachings = getTeachings("default");
  const worktrees = getActiveWorktrees();
  const recentUsage = getRecentUsage(5);

  const blocks: any[] = [
    { type: "header", text: { type: "plain_text", text: "Claude Code Dashboard" } },
    { type: "context", elements: [{ type: "mrkdwn", text: `Last updated: ${new Date().toLocaleString()}` }] },
    { type: "divider" },
    { type: "section", fields: [
      { type: "mrkdwn", text: `*Active Sessions:*\n${sessions.length}` },
      { type: "mrkdwn", text: `*Team Teachings:*\n${teachings.length}` },
      { type: "mrkdwn", text: `*Active Worktrees:*\n${worktrees.length}` },
      { type: "mrkdwn", text: `*Running Processes:*\n${activeProcesses.size}` },
    ]},
    { type: "divider" },
  ];

  if (sessions.length > 0) {
    blocks.push({ type: "header", text: { type: "plain_text", text: "Recent Sessions" } });
    for (const s of sessions.slice(0, 10)) {
      const statusIcon = activeProcesses.has(s.channel_id) ? ":large_green_circle:" : ":white_circle:";
      blocks.push({
        type: "section",
        text: { type: "mrkdwn", text: `${statusIcon} \`${s.cwd || "no cwd"}\`\n_Updated: ${s.updated_at}_` },
      });
    }
    blocks.push({ type: "divider" });
  }

  if (recentUsage.length > 0) {
    blocks.push({ type: "header", text: { type: "plain_text", text: "Recent Activity" } });
    for (const u of recentUsage) {
      blocks.push({
        type: "section",
        text: { type: "mrkdwn", text: `*${u.model || "claude"}* \u2014 ${u.num_turns} turn(s), $${(u.total_cost_usd || 0).toFixed(4)} \u2014 _${u.created_at}_` },
      });
    }
    blocks.push({ type: "divider" });
  }

  blocks.push(
    { type: "header", text: { type: "plain_text", text: "Quick Actions" } },
    {
      type: "actions",
      elements: [
        {
          type: "button",
          text: { type: "plain_text", text: "View Teachings" },
          action_id: "home_view_teachings",
        },
        {
          type: "button",
          text: { type: "plain_text", text: "Add Teaching" },
          action_id: "home_add_teaching",
          style: "primary",
        },
      ],
    }
  );

  return blocks;
}
